
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuixglzrkqasnlttcefq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aXhnbHpya3Fhc25sdHRjZWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTAxMjgsImV4cCI6MjA2MDk4NjEyOH0.Skt1hq9fnqemevFOaomkC3wTAWpWFMM1eFJhwobZH8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true, // This enables session persistence
      autoRefreshToken: true, // This enables automatic token refresh
      detectSessionInUrl: true // This detects the session in URL for OAuth flows
    }
  }
);

// Helper function to generate a UUID from a string
export function generateUUID() {
  return crypto.randomUUID();
}
